# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Building-Systems
tagline:             'Code, music and travel'
description:         'A place for letting out steam, sharing experiences and ideas'
url:                 http://building-systems.xyz
baseurl:             ''
paginate:            5
paginate_path:      "page:num"

# About/contact
author:
  name:              Bhargav Voleti
  url:               https://twitter.com/2093bps
  email:             bhargav.voleti93@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
